foreground         #c4c3c9
background         #141027
background_opacity 1.0
cursor             #c4c3c9

active_tab_foreground     #141027
active_tab_background     #c4c3c9
inactive_tab_foreground   #c4c3c9
inactive_tab_background   #141027

active_border_color   #c4c3c9
inactive_border_color #141027
bell_border_color     #7f06ab

color0       #141027
color8       #645f75
color1       #7f06ab
color9       #AA09E4
color2       #b408a1
color10      #F10BD7
color3       #ba53b2
color11      #F86FEE
color4       #a072b1
color12      #D698EC
color5       #ba6cb8
color13      #F991F6
color6       #b782bb
color14      #F5AEFA
color7       #94929d
color15      #c4c3c9
