foreground         #c5c4c4
background         #181316
background_opacity 1.0
cursor             #c5c4c4

active_tab_foreground     #181316
active_tab_background     #c5c4c4
inactive_tab_foreground   #c5c4c4
inactive_tab_background   #181316

active_border_color   #c5c4c4
inactive_border_color #181316
bell_border_color     #93576d

color0       #181316
color8       #705c69
color1       #93576d
color9       #C47492
color2       #7e7279
color10      #A898A2
color3       #b0807b
color11      #EBABA4
color4       #b99a84
color12      #F7CEB1
color5       #bd7492
color13      #FD9BC3
color6       #b7a097
color14      #F4D6CA
color7       #9a9097
color15      #c5c4c4
